const textToIm = require("text-to-image");
const fs = require("fs");

const commonFirstNames = [
  "Christopher",
  "Jim",
  "James",
  "Jimmy",
  "Mary",
  "John",
  "Jay",
  "Patricia",
  "Pat",
  "Robert",
  "Rob",
  "Jennifer",
  "Jen",
  "Michael",
  "Mike",
  "Elizabeth",
  "Liz",
  "William",
  "Will",
  "Linda",
  "David",
  "Dave",
  "Barbara",
  "Barb",
  "Richard",
  "Rich",
  "Susan",
  "Sue",
  "Joseph",
  "Joe",
  "Jessica",
  "Jess",
  "Thomas",
  "Tom",
  "Margaret",
  "Charles",
  "Chuck",
  "Sarah",
  "Chris",
  "Callum",
  "Karen",
  "Daniel",
  "Dan",
  "Dana",
  "Dani",
  "Nancy",
  "Matthew",
  "Matt",
  "Betty",
  "Betsy",
  "Anthony",
  "Tony",
  "Lisa",
  "Donald",
  "Don",
  "Dorothy",
  "Mark",
  "Sandra",
  "Paul",
  "Ashley",
  "Steven",
  "Steve",
  "Kimberly",
  "Kim",
  "Andrew",
  "Drew",
  "Donna",
  "Kenneth",
  "Ken",
  "Carol",
  "George",
  "Michelle",
  "Joshua",
  "Josh",
  "Emily",
  "Kevin",
  "Amanda",
  "Brian",
  "Helen",
  "Edward",
  "Ed",
  "Melissa",
  "Ronald",
  "Ron",
  "Deborah",
  "Deb",
  "Timothy",
  "Tim",
  "Stephanie",
  "Steph",
  "Jason",
  "Laura",
  "Jeffrey",
  "Jeff",
  "Rebecca",
  "Becca",
  "Ryan",
  "Sharon",
  "Gary",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Nicholas",
  "Nick",
  "Amy",
  "Eric",
  "Shirley",
  "Stephen",
  "Steve",
  "Anna",
  "Jonathan",
  "Angela",
  "Larry",
  "Ruth",
  "Justin",
  "Brenda",
  "Scott",
  "Pamela",
  "Frank",
  "Nicole",
  "Brandon",
  "Katherine",
  "Raymond",
  "Muizz",
  "Virginia",
  "Gregory",
  "Greg",
  "Catherine",
  "Cat",
  "Benjamin",
  "Ben",
  "Christine",
  "Samuel",
  "Sam",
  "Samantha",
  "Patrick",
  "Deb",
  "Debra",
  "Alexander",
  "Alex",
  "Janet",
  "Jack",
  "Rachel",
  "Dennis",
  "Carolyn",
  "Jerry",
  "Emma",
  "Tyler",
  "Maria",
  "Aaron",
  "Heather",
  "Henry",
  "Diane",
  "Douglas",
  "Doug",
  "Julie",
  "Jose",
  "Joyce",
  "Peter",
  "Pete",
  "Evelyn",
  "Adam",
  "Frances",
  "Zachary",
  "Zach",
  "Joan",
  "Nathan",
  "Nate",
  "Christina",
  "Tina",
  "Walter",
  "Walt",
  "Kelly",
  "Harold",
  "Victoria",
  "Vic",
  "Kyle",
  "Lauren",
  "Carl",
  "Martha",
  "Arthur",
  "Judith",
  "Gerald",
  "Cheryl",
  "Roger",
  "Megan",
  "Keith",
  "Andrea",
  "Jeremy",
  "Ann",
  "Terry",
  "Alice",
  "Lawrence",
  "Jean",
  "Sean",
  "Doris",
  "Christian",
  "Jacqueline",
  "Albert",
  "Kathryn",
  "Joe",
  "Hannah",
  "Ethan",
  "Olivia",
  "Austin",
  "Gloria",
  "Jesse",
  "Marie",
  "Willie",
  "Teresa",
  "Billy",
  "Sara",
  "Bryan",
  "Janice",
  "Bruce",
  "Julia",
  "Jordan",
  "Grace",
  "Ralph",
  "Judy",
  "Roy",
  "Theresa",
  "Noah",
  "Rose",
  "Dylan",
  "Beverly",
  "Eugene",
  "Denise",
  "Wayne",
  "Marilyn",
  "Alan",
  "Amber",
  "Juan",
  "Madison",
  "Louis",
  "Danielle",
  "Russell",
  "Brittany",
  "Gabriel",
  "Diana",
  "Randy",
  "Abigail",
  "Abby",
  "Philip",
  "Phil",
  "Jane",
  "Harry",
  "Natalie",
  "Vincent",
  "Vince",
  "Lori",
  "Bobby",
  "Bob",
  "Tiffany",
  "Johnny",
  "Alexis",
  "Logan",
  "Kayla",
];

// const run = async () => {
//   for (let i = 0; i < 2; i++) {
//     console.log("running for", commonFirstNames[i]);
//     const dataUri = await textToIm.generate(commonFirstNames[i], {
//       fontFamily: "ReenieBeanie",
//       fontPath: "./reenieBeanie.ttf",
//       fontSize: 40,
//       bgColor: "#1F1CAF00",
//       textColor: "#FFFFFF",
//       maxWidth: 180,
//       textAlign: "center",
//       marin: 0,
//     });

//     const buffer = Buffer.from(dataUri.split(",")[1], "base64");

//     await fs.writeFileSync(`${commonFirstNames[i]}.png`, buffer);
//   }
// };

//run();

const run = async (start, end, style, font = "reenieBeanie") => {
  console.log("Generating images...");

  for (let wager = start; wager <= end; wager++) {
    const dataUri = textToIm.generateSync(
      `${style === "won" ? "+" : "-"}$${wager}`,
      {
        fontFamily: font,
        fontPath: "./reenieBeanie.ttf",
        fontSize: 40,
        bgColor: "#1F1CAF00",
        textColor: style === "won" ? "#00FF00" : "#FF0000",
        maxWidth: 80,
        textAlign: "center",
        margin: 0,
      }
    );

    const buffer = Buffer.from(dataUri.split(",")[1], "base64");
    fs.writeFileSync(`./wagers/${wager}.png`, buffer);

    console.log(`Complete for (${style}) $${wager}`);
  }
  console.log("Image generation complete!");
};

run(1, 3, "won");
